In [1]:
def square(n):
    return n*n
square(4)

16

In [3]:
sq=lambda n:n*n
sq(5)

25

In [4]:
def sum1(a,b):
    return a+b
sum1(2,3)

5

In [5]:
summation=lambda a,b:a+b
summation(2,3)

5

In [6]:
a=input()
type(a)

hello


str

In [2]:
"""Map convers
string to int"""
l=list(map(int,input().split()))

1 2 3 4 5


In [3]:
l

[1, 2, 3, 4, 5]

In [5]:
list1=[1,2,3,4,5]
list2=[]
for i in list1:
    list2.append(i**2)
list2

[1, 4, 9, 16, 25]

# Python Libraries

In [6]:
"""
1. Pandas---> Data Manipulation, Cleaning
2. NumPy---> Data Processing
3. SeaBorn & Matplotlib---> Data Visualization
"""

'\n1. Pandas---> Data Manipulation, Cleaning\n2. NumPy---> Data Processing\n3. SeaBorn & Matplotlib---> Data Visualization\n'

# 1-D Array

In [8]:
import numpy as np
a=np.array([1,2,3])
print(a)

[1 2 3]


# 2-D Array

In [10]:
import numpy as np
b=np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


# Arrange the numbers between x and y

In [14]:
import numpy as np
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

# Arrange 'z' numbers between x and y

In [20]:
import numpy as np
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [23]:
np.linspace(0,15,8)

array([ 0.        ,  2.14285714,  4.28571429,  6.42857143,  8.57142857,
       10.71428571, 12.85714286, 15.        ])

In [25]:
np.full((4,4),-1)

array([[-1, -1, -1, -1],
       [-1, -1, -1, -1],
       [-1, -1, -1, -1],
       [-1, -1, -1, -1]])

In [28]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

# Filling RANDOM in 1-D Dimention an Array 

In [33]:
np.random.random((2,3))

array([[0.01996283, 0.23657697, 0.37435366],
       [0.39279379, 0.62382584, 0.43035668]])

In [45]:
s=np.random.random((2,6))
s

array([[0.18131815, 0.83727325, 0.27166717, 0.93918186, 0.56976376,
        0.01583263],
       [0.08214146, 0.43202214, 0.38613919, 0.75054557, 0.54691384,
        0.07310438]])

In [46]:
s.shape

(2, 6)

In [47]:
s.shape=(3,4)
s

array([[0.18131815, 0.83727325, 0.27166717, 0.93918186],
       [0.56976376, 0.01583263, 0.08214146, 0.43202214],
       [0.38613919, 0.75054557, 0.54691384, 0.07310438]])

In [48]:
s.shape

(3, 4)

In [49]:
np.sum([2,4])

6

In [50]:
np.sum([[1,2],[3,4]],axis=0)

array([4, 6])

In [52]:
np.sum([[1,2],[3,4]],axis=1)

array([3, 7])

In [53]:
np.sum([[1,2],[3,4]])

10

In [57]:
a=[1,2,3,4,5,6,7,8,9,10]
print("Sum: ",np.sum(a))
print("Minimum: ",np.min(a))
print("Maximum: ",np.max(a))
print("Mean: ",np.mean(a))
print("Median: ",np.median(a))
print("Correlation Coefficient: ",np.corrcoef(a))
print("Standard Deviation: ",np.std(a))

Sum:  55
Minimum:  1
Maximum:  10
Mean:  5.5
Median:  5.5
Correlation Coefficient:  1.0
Standard Deviation:  2.8722813232690143


# Concept of Broadcasting

In [67]:
a=np.array([[1,2,3],[4,5,6],[5,6,7]])
b=np.array([[0,1,2]])
print("First Array: \n",a,"\n")
print("Second Array: \n",b,"\n")
print("First Array + Second Array: \n",a+b,"\n")

First Array: 
 [[1 2 3]
 [4 5 6]
 [5 6 7]] 

Second Array: 
 [[0 1 2]] 

First Array + Second Array: 
 [[1 3 5]
 [4 6 8]
 [5 7 9]] 



# Array manipulation in Python

In [69]:
a=np.array([1,2,3])
b=np.array([4,5,6])
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6])

In [70]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

In [71]:
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [72]:
np.column_stack((a,b))

array([[1, 4],
       [2, 5],
       [3, 6]])